server: server.cpp broadcast_udpHeart.h recv_tcp_heartPacket.h wait_user_cmd_exec.h
	g++ -g server.cpp broadcast_udpHeart.h recv_tcp_heartPacket.h wait_user_cmd_exec.h -o server -lpthread -lglog

clean:
	rm server
	rm ./.log/
	rm ./*_temp


